apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
    - name: ssh
      port: 22
  type: LoadBalancer
  loadBalancerIP: 192.168.49.50

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: my_nginx
        imagePullPolicy: Never
        name: nginx
